# Workflow para desplegar contenido estático en GitHub Pages
name: Deploy static content to Pages

on:
  push:
    branches: ['main'] # Ejecutar cuando se hace push en la rama 'main'
  workflow_dispatch: # Permite ejecutar el flujo manualmente

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      # 1. Descargar el código fuente
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Configurar Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18 # Recomendado LTS
          cache: 'npm'

      # 3. Instalar dependencias
      - name: Install dependencies
        run: npm ci

      # 4. Construir el proyecto
      - name: Build project
        run: npm run build

      # 5. Configurar GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v4

      # 6. Subir artefactos
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist' # Asegúrate de que sea la carpeta de salida correcta

      # 7. Desplegar a GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
